# This is a sample build configuration for 
# Agiledrop - Bitbucket pipelines - Pantheon Workflow 
# 
image: drupal:8-apache

pipelines:
  branches:
    develop:
      - step:
          name: Agiledrop Bitbucket pipelines - Pantheon Workflow
          caches:
            - composer
          script:
            - apt-get update  && apt-get -y upgrade
            - apt-get install -y unzip git gnupg
            - curl -sL https://deb.nodesource.com/setup_8.x | bash -
            - apt-get install -y nodejs
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - /bin/cp -f scripts/bitbucket-pipelines/.gitignore .gitignore
            - rm -Rf .git
            - composer install
            - cd $BITBUCKET_CLONE_DIR/themes/custom/mat/.npm
            - npm install
            - npm install -g gulp
            - gulp build
            - cd $BITBUCKET_CLONE_DIR
            - sh scripts/bitbucket-pipelines/cleanup.sh  
            - echo "Debugging ...."
            - echo $SSH_HOST >> ~/.ssh/known_hosts
            - cat /opt/atlassian/pipelines/agent/data/id_rsa > ~/.ssh/id_rsa
            - echo "Cloning ..."
            - git clone $PANTHEON_REPO $PANTHEON_CODE_PATH
            - cd $PANTHEON_CODE_PATH
            - /bin/cp -rf $BITBUCKET_CLONE_DIR/. .
            - git config --global user.name "$GIT_USER"
            - git config --global user.email $GIT_EMAIL
            - git config core.autocrlf false
            - git add -A
            - git status
            - git commit -am "Deploying build nr. $BITBUCKET_BUILD_NUMBER ($BITBUCKET_COMMIT)."
#            - git push

