# This is a sample build configuration for 
# Agiledrop - Bitbucket pipelines - Pantheon Workflow 
# 
image: drupal:8-apache

pipelines:
  branches:
    develop:
      - step:
          name: Agiledrop Bitbucket pipelines - Pantheon Workflow
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip git 
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - /bin/cp -f scripts/bitbucket-pipelines/.gitignore .gitignore
            - rm -Rf .git
            - composer install
            - sh scripts/bitbucket-pipelines/cleanup.sh  
            - echo "Debugging ...."
            - echo $SSH_HOST >> ~/.ssh/known_hosts
            - cat /opt/atlassian/pipelines/agent/data/id_rsa > ~/.ssh/id_rsa
            - echo "Cloning ..."
            - git clone $PANTHEON_REPO $PANTHEON_CODE_PATH
            - cd $PANTHEON_CODE_PATH
            - /bin/cp -rf $BITBUCKET_CLONE_DIR/. .
            - git config --global user.name "$GIT_USER"
            - git config --global user.email $GIT_EMAIL
            - git config core.autocrlf false
            - git add -A
            - git rm --cached modules/contrib/install_profile_generator
            - git add -f modules/contrib/install_profile_generator
            - git rm --cached modules/contrib/media_entity_browser
            - git add -f modules/contrib/media_entity_browser
            - git rm --cached modules/contrib/slick_paragraphs
            - git add -f modules/contrib/slick_paragraphs
            - git rm -cached profiles/contrib/tdx-distribution/
            - git add -f profiles/contrib/tdx-distribution/
            - git clean -ndX
            - git commit -am "Deploying build nr. $BITBUCKET_BUILD_NUMBER ."
            - git push

