<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;

function mat_search_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-search-page-1') {
    $form['search_api_fulltext']['#attributes']['placeholder'] = t('Type here ...');
    $form['actions']['submit']['#value'] = t('Search');
  }
}

function mat_search_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'search' && $view->current_display == 'page_1') {
    $params = \Drupal::request()->query->all();
    if (!empty($params['search_api_fulltext'])) {
      $query = '<h1 class="search-query-text">"'.$params['search_api_fulltext'].'"</h1>';
      $view->header['result']->options['content'] = $view->header['result']->options['content'].' '.$query;
    } else {
      $query = '';
      $view->header['result']->options['content'] = '';
    }
  }
}

function mat_search_node_presave(EntityInterface $node) {
  $meta_field = $node->get('field_meta_tags');
  if($meta_field->first() != null) {
    $metatag_list = unserialize($meta_field->first()->value);
  }
  if (isset($metatag_list['description'])) {
    $node->set('field_excerpt', $metatag_list['description']);
  }

}
