buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\">facebook share</a>\r\n<a class=\"a2a_button_twitter\">twitter share</a>\r\n<a class=\"a2a_button_google_plus\">google plus share</a>\r\n"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
_core:
  default_config_hash: NDRF3_W0gH1bvlrc08ompcnvuyoZRqmkYMIgNNwuAlk
