ignored_config_entities:
  0: mat_story.settings
  2: mat_storyaudio.settings
  4: 'views.view.news_landing:display.default.display_options.header.entity_block_content.target'
  6: 'views.view.news_landing:dependencies.content'
  8: 'system.site:page.403'
  10: 'system.site:page.404'
  12: 'recaptcha.settings:site_key'
  14: 'recaptcha.settings:secret_key'
  16: swiftmailer.transport
  18: webform.settings
  20: 'webform.webform.*'
  22: ~webform.webform.paypal_donation_form
  24: ~webform.webform.dla_registry_create_registrant
_core:
  default_config_hash: d61606zZ1cuO6QeNJ4JDpfDp8hxuV2qQh9LaqUk8si0
