module:
  addtoany: 0
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  better_exposed_filters: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  classy_paragraphs: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  content_moderation: 0
  contextual: 0
  contribute: 0
  cotailored_base_drush_commands: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  install_profile_generator: 0
  language: 0
  link: 0
  mailsystem: 0
  mat_global: 0
  mat_news: 0
  mat_search: 0
  mat_story: 0
  mat_webform: 0
  media: 0
  media_entity_browser: 0
  menu_block: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_edit: 0
  path: 0
  recreate_block_content: 0
  responsive_image: 0
  search_api: 0
  search_api_db: 0
  slick: 0
  slick_paragraphs: 0
  svg_image: 0
  swiftmailer: 0
  switch_page_theme: 0
  syslog: 0
  system: 0
  tab_toolbar: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  tdx: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  tdx_adminal: 0
  tdx_base: 0
  tdx_wireframe: 0
  mat: 0
profile: tdx
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
