mat_story:
  email: admin@technivant.com
  user_title: 'Email title for user (edit in admin)'
  user_content:
    value: "<p>This is email content, edited in administration.</p>\r\n"
    format: rich_editor
  story_submitted:
    value: "<h1>Thank You</h1>\r\n\r\n<h4>Thank you for taking the time to submit your story. Whether it is your own personal experience or the story of a loved one, we appreciate your willingness to share the impact donation has had on your life.</h4>\r\n\r\n<p>A member of our team will review your story and reach out with questions or a notification that your story has been published on the site.</p>\r\n\r\n<p>Questions? Email <a href=\"mailto:info@midamericatransplant.org\">info@midamericatransplant.org</a>.</p>\r\n\r\n<a href=\"/stories\" class=\"btn-go-back\">Return to All Stories</a>\r\n"
    format: advanced
