mat_story:
  email: 'Darjan Pezer <darjan.pezer@agiledrop.com>, Mitja Krope <mitja.krope@agiledrop.com>'
  user_title: 'Email title for user (edit in admin)'
  user_content:
    value: "<p>This is email content, edited in administration.</p>\r\n"
    format: rich_editor
