mat_story:
  email: 'Demo User <demo.user@mat.com>, John Doe <john.doe@gmail.com>'
  user_title: 'Email title for user (edit in admin)'
  user_content:
    value: "<p>This is email content, edited in administration.</p>\r\n"
    format: rich_editor
