transport: smtp
smtp_host: mail.yourserver.com
smtp_port: 25
smtp_encryption: '0'
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
spool_directory: ''
_core:
  default_config_hash: uZ7W_b5GvIzwpiq0AjUnFzCKnhs-b_nx3IQbJns8q8U
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: username@email.com
    password: password
