favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: true
_core:
  default_config_hash: 0tC3qj48-2PQHc-xwGl-Ps60Sst5VhzB0xIEM5dGJNc
