<?php
use Drupal\Core\Form\FormStateInterface;

function mat_news_form_alter(&$form, $form_state, $form_id) {
  if(isset($form['#id']) && $form['#id'] == 'views-exposed-form-news-landing-page-1') {
    $form['field_news_category_target_id']['#type'] = 'radios';
    // get years
    $nids = \Drupal::entityQuery('node')->condition('type','news_article')->execute();
    $nodes =  \Drupal\node\Entity\Node::loadMultiple($nids);
    $years = array();
    foreach ($nodes as $k => $v) {
      $get_year = date('Y', $v->getCreatedTime());
      $years[$get_year] = $get_year;
    }
    $years_clean = array_unique($years);
    $cur_year = date('Y');
    $form['year'] = [
      '#title' => t('Archive'),
      '#type' => 'radios',
      '#options' => $years_clean,
      '#size' => NULL,
      '#default_value' => $cur_year,
    ];

    $form['field_news_category_target_id']['#options']['All'] = t('Show all');
  }
}

function mat_news_views_query_alter(\Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\Sql $query) {
  if ($view->id() == 'news_landing') {
    // Prepare a placeholder from exposed form.
    $placeholders = [':input_year' => $view->exposed_raw_input["year"]];

    // Add a tableAlias (which is not added automatically) and prepare a formula for condition.
    $view->argument["created_year"]->tableAlias = 'node_field_data';
    $formula_year = $view->argument["created_year"]->getDateFormat('Y') . ' = :input_year';

    // Add condition to query.
    $query->addWhere(0, $formula_year, $placeholders, 'formula');
  }
}